# Generated by Django 5.2.11 on 2026-04-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_foodorder_status_foodcomplaint_foodreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='payment_method',
            field=models.CharField(default='COD', max_length=50),
        ),
    ]
