# Generated by Django 5.2.11 on 2026-04-08 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_foodorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='foods.foodorder'),
        ),
    ]
