# Generated by Django 5.2.11 on 2026-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_foodreview_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='ordered_items',
            field=models.TextField(blank=True, help_text='Summary of items ordered', null=True),
        ),
    ]
