# Generated by Django 5.2.11 on 2026-04-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0002_busseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buses/'),
        ),
    ]
