# Generated by Django 5.2.11 on 2026-04-08 01:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0004_busbooking_customer_email_busbooking_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='price_per_seat',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='source',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='total_seats',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busseat',
            name='bus',
        ),
        migrations.AddField(
            model_name='bus',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='busseat',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField(default=django.utils.timezone.now)),
                ('timing_shift', models.CharField(help_text='e.g. 6:00 AM, Morning, Night', max_length=100)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_seats', models.IntegerField(default=40)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='travellers.bus')),
            ],
        ),
        migrations.AddField(
            model_name='busbooking',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travellers.trip'),
        ),
        migrations.AddField(
            model_name='busseat',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='travellers.trip'),
        ),
    ]
