# Generated by Django 5.2.11 on 2026-04-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellers', '0005_remove_bus_arrival_time_remove_bus_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='payment_method',
            field=models.CharField(default='COD', max_length=50),
        ),
    ]
