# Generated by Django 5.2.11 on 2026-03-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('from_city', models.CharField(max_length=200)),
                ('to_city', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
