# Generated by Django 5.2.11 on 2026-04-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movieticket_customer_email_movieticket_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieticket',
            name='payment_method',
            field=models.CharField(default='COD', max_length=50),
        ),
    ]
