# Generated by Django 5.2.11 on 2026-04-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movieticket_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('location_url', models.URLField(blank=True, help_text='Google Maps link or similar', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='theater_name',
            field=models.CharField(help_text="Legacy field, use 'theater' for new entries", max_length=200),
        ),
        migrations.AddField(
            model_name='show',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.theater'),
        ),
    ]
