# Generated by Django 5.2.11 on 2026-05-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_theater_alter_show_theater_name_show_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='theaters/'),
        ),
    ]
