# Generated by Django 5.2.11 on 2026-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_shoppingcart_shoppingcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('clothing_female', 'Clothing - Female'), ('clothing_male', 'Clothing - Male'), ('clothing_kids', 'Clothing - Kids'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
