# Generated by Django 5.2.11 on 2026-03-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorder',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppingorder',
            name='delivery_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingorder',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
