# Generated by Django 5.2.11 on 2026-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shoppingorderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
