# Generated by Django 5.2.11 on 2026-04-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_shoppingorder_delivered_at_shoppingorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorder',
            name='is_fast_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingorder',
            name='payment_method',
            field=models.CharField(default='COD', max_length=50),
        ),
    ]
