# Generated by Django 5.2.11 on 2026-04-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_shoppingorder_is_fast_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorder',
            name='current_location',
            field=models.CharField(blank=True, help_text="Order tracking status (e.g. 'At Hyderabad Hub')", max_length=255, null=True),
        ),
    ]
