# Generated by Django 5.2.11 on 2026-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_shoppingorder_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorder',
            name='agent_phone',
            field=models.CharField(blank=True, help_text='Delivery agent contact number', max_length=20, null=True),
        ),
    ]
