# Generated by Django 5.2.11 on 2026-04-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_shoppingorder_agent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingorder',
            name='expected_delivery',
            field=models.DateTimeField(blank=True, help_text='Expected date and time of delivery', null=True),
        ),
        migrations.AddField(
            model_name='shoppingorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
