# Generated by Django 5.2.11 on 2026-04-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_shoppingorder_expected_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='e.g. S, M, L, XL (Comma separated)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Red, Blue, Black', max_length=50, null=True),
        ),
    ]
