# Generated by Django 5.2.11 on 2026-05-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_product_available_sizes_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='shoppingorderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantities',
            field=models.CharField(blank=True, help_text='e.g. 500g, 1kg, 2 liters (Comma separated)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_name',
            field=models.CharField(blank=True, help_text='e.g. Salt, Soap, Shampoo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shoppingorderitem',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
